version: '3'
services:
  service-registry:
    build:
      context: ./service-registry
    ports:
      - "8761:8761"
    networks:
      - microservice-network

  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - service-registry
    networks:
      - microservice-network

  product-service:
    build:
      context: ./product-service
    ports:
      - "8081:8081"
      - "8180:8180"
    depends_on:
      - service-registry
    networks:
      - microservice-network

  offer-service:
    build:
      context: ./offer-service
    ports:
      - "8082:8082"
    depends_on:
      - service-registry
    networks:
      - microservice-network

  microservice-ui:
    build:
      context: ./microservice-ui
    ports:
      - "80:80"
    networks:
      - microservice-network

  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - microservice-network

networks:
  microservice-network:
    driver: bridge
